/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 scene.gltf --transfor 
*/
import { useGLTF } from '@react-three/drei'

export function Scene(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.bg.geometry} material={materials['bg']} />
      <mesh geometry={nodes.lines.geometry} material={materials['line']} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
